const stripe_event_session = {
  id: "in_1RmBv2LAxh7V2BxLsfP3aody",
  object: "invoice",
  account_country: "GB",
  account_name: "Virstaf LTD",
  account_tax_ids: null,
  amount_due: 0,
  amount_overpaid: 0,
  amount_paid: 0,
  amount_remaining: 0,
  amount_shipping: 0,
  application: null,
  attempt_count: 0,
  attempted: true,
  auto_advance: false,
  automatic_tax: {
    disabled_reason: null,
    enabled: false,
    liability: null,
    provider: null,
    status: null,
  },
  automatically_finalizes_at: null,
  billing_reason: "subscription_create",
  collection_method: "charge_automatically",
  created: 1752836016,
  currency: "gbp",
  custom_fields: null,
  customer: "cus_Shb70yNnR4rmDW",
  customer_address: null,
  customer_email: "nored17748@lhory.com",
  customer_name: null,
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: "none",
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discounts: [],
  due_date: null,
  effective_at: 1752836016,
  ending_balance: 0,
  footer: null,
  from_invoice: null,
  hosted_invoice_url:
    "https://invoice.stripe.com/i/acct_1L35V5LAxh7V2BxL/test_YWNjdF8xTDM1VjVMQXhoN1YyQnhMLF9TaGI3bmNaVmRyNklTMXhWN2p2dmN1ZzNhYlJ4cXF1LDE0MzM3NjgxNw0200fMxnBkuo?s=ap",
  invoice_pdf:
    "https://pay.stripe.com/invoice/acct_1L35V5LAxh7V2BxL/test_YWNjdF8xTDM1VjVMQXhoN1YyQnhMLF9TaGI3bmNaVmRyNklTMXhWN2p2dmN1ZzNhYlJ4cXF1LDE0MzM3NjgxNw0200fMxnBkuo/pdf?s=ap",
  issuer: { type: "self" },
  last_finalization_error: null,
  latest_revision: null,
  lines: {
    object: "list",
    data: [
      {
        id: "il_1RmGthLAxh7V2BxL2TVulafD",
        object: "line_item",
        amount: 0,
        currency: "gbp",
        description: "Trial period for Silver",
        discount_amounts: [],
        discountable: true,
        discounts: [],
        invoice: "in_1RmGthLAxh7V2BxLqSneJD3Y",
        livemode: false,
        metadata: {
          email: "nored17748@lhory.com",
          userId: "c22c785d-c8be-43dd-96bc-f6ae9d66ca1d",
        },
        parent: {
          invoice_item_details: null,
          subscription_item_details: {
            invoice_item: null,
            proration: false,
            proration_details: { credited_items: null },
            subscription: "sub_1RmaN3LAxh7V2BxL2Xm6XsqS",
            subscription_item: "si_Si0NonL2bUFv9y",
          },
          type: "subscription_item_details",
        },
        period: { end: 1753459953, start: 1752855153 },
        pretax_credit_amounts: [],
        pricing: {
          price_details: {
            price: "price_1RfmqFLAxh7V2BxLt2hMnLTc",
            product: "prod_Sayn8WtloqIH6C",
          },
          type: "price_details",
          unit_amount_decimal: "0",
        },
        quantity: 1,
        taxes: [],
      },
    ],
    has_more: false,
    total_count: 1,
    url: "/v1/invoices/in_1RmBv2LAxh7V2BxLsfP3aody/lines",
  },
  livemode: false,
  metadata: {},
  next_payment_attempt: null,
  number: "1AF11EFE-0041",
  on_behalf_of: null,
  parent: {
    quote_details: null,
    subscription_details: {
      metadata: {
        email: "kedaki1034@dosonex.com",
        userId: "093670a8-6fdb-47f4-92da-21b832d11013",
      },
      subscription: "sub_1RmBv2LAxh7V2BxLZ40pW0La",
    },
    type: "subscription_details",
  },
  payment_settings: {
    default_mandate: null,
    payment_method_options: {
      acss_debit: null,
      bancontact: null,
      card: [Object],
      customer_balance: null,
      konbini: null,
      sepa_debit: null,
      us_bank_account: null,
    },
    payment_method_types: null,
  },
  period_end: 1752836016,
  period_start: 1752836016,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  receipt_number: null,
  rendering: null,
  shipping_cost: null,
  shipping_details: null,
  starting_balance: 0,
  statement_descriptor: null,
  status: "paid",
  status_transitions: {
    finalized_at: 1752836016,
    marked_uncollectible_at: null,
    paid_at: 1752836016,
    voided_at: null,
  },
  subtotal: 0,
  subtotal_excluding_tax: 0,
  test_clock: null,
  total: 0,
  total_discount_amounts: [],
  total_excluding_tax: 0,
  total_pretax_credit_amounts: [],
  total_taxes: [],
  webhooks_delivered_at: null,
};
