const stripeSubscriptionSession = {
  id: "in_1RmBv2LAxh7V2BxLsfP3aody",
  object: "invoice",
  account_country: "GB",
  account_name: "Virstaf LTD",
  account_tax_ids: null,
  amount_due: 0,
  amount_overpaid: 0,
  amount_paid: 0,
  amount_remaining: 0,
  amount_shipping: 0,
  application: null,
  attempt_count: 0,
  attempted: true,
  auto_advance: false,
  automatic_tax: {
    disabled_reason: null,
    enabled: false,
    liability: null,
    provider: null,
    status: null,
  },
  automatically_finalizes_at: null,
  billing_reason: "subscription_create",
  collection_method: "charge_automatically",
  created: 1752836016,
  currency: "gbp",
  custom_fields: null,
  customer: "cus_Shb70yNnR4rmDW",
  customer_address: null,
  customer_email: "nored17748@lhory.com",
  customer_name: null,
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: "none",
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discounts: [],
  due_date: null,
  effective_at: 1752836016,
  ending_balance: 0,
  footer: null,
  from_invoice: null,
  hosted_invoice_url:
    "https://invoice.stripe.com/i/acct_1L35V5LAxh7V2BxL/test_YWNjdF8xTDM1VjVMQXhoN1YyQnhMLF9TaGI3bmNaVmRyNklTMXhWN2p2dmN1ZzNhYlJ4cXF1LDE0MzM3NjgxNw0200fMxnBkuo?s=ap",
  invoice_pdf:
    "https://pay.stripe.com/invoice/acct_1L35V5LAxh7V2BxL/test_YWNjdF8xTDM1VjVMQXhoN1YyQnhMLF9TaGI3bmNaVmRyNklTMXhWN2p2dmN1ZzNhYlJ4cXF1LDE0MzM3NjgxNw0200fMxnBkuo/pdf?s=ap",
  issuer: { type: "self" },
  last_finalization_error: null,
  latest_revision: null,
  lines: {
    object: "list",
    data: [
      {
        id: "il_1RmGthLAxh7V2BxL2TVulafD",
        object: "line_item",
        amount: 0,
        currency: "gbp",
        description: "Trial period for Silver",
        discount_amounts: [],
        discountable: true,
        discounts: [],
        invoice: "in_1RmGthLAxh7V2BxLqSneJD3Y",
        livemode: false,
        metadata: {
          email: "nored17748@lhory.com",
          userId: "c22c785d-c8be-43dd-96bc-f6ae9d66ca1d",
        },
        parent: {
          invoice_item_details: null,
          subscription_item_details: {
            invoice_item: null,
            proration: false,
            proration_details: { credited_items: null },
            subscription: "sub_1RmaN3LAxh7V2BxL2Xm6XsqS",
            subscription_item: "si_Si0NonL2bUFv9y",
          },
          type: "subscription_item_details",
        },
        period: { end: 1753459953, start: 1752855153 },
        pretax_credit_amounts: [],
        pricing: {
          price_details: {
            price: "price_1RfmqFLAxh7V2BxLt2hMnLTc",
            product: "prod_Sayn8WtloqIH6C",
          },
          type: "price_details",
          unit_amount_decimal: "0",
        },
        quantity: 1,
        taxes: [],
      },
    ],
    has_more: false,
    total_count: 1,
    url: "/v1/invoices/in_1RmBv2LAxh7V2BxLsfP3aody/lines",
  },
  livemode: false,
  metadata: {},
  next_payment_attempt: null,
  number: "1AF11EFE-0041",
  on_behalf_of: null,
  parent: {
    quote_details: null,
    subscription_details: {
      metadata: {
        email: "kedaki1034@dosonex.com",
        userId: "093670a8-6fdb-47f4-92da-21b832d11013",
      },
      subscription: "sub_1RmBv2LAxh7V2BxLZ40pW0La",
    },
    type: "subscription_details",
  },
  payment_settings: {
    default_mandate: null,
    payment_method_options: {
      acss_debit: null,
      bancontact: null,
      card: [Object],
      customer_balance: null,
      konbini: null,
      sepa_debit: null,
      us_bank_account: null,
    },
    payment_method_types: null,
  },
  period_end: 1752836016,
  period_start: 1752836016,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  receipt_number: null,
  rendering: null,
  shipping_cost: null,
  shipping_details: null,
  starting_balance: 0,
  statement_descriptor: null,
  status: "paid",
  status_transitions: {
    finalized_at: 1752836016,
    marked_uncollectible_at: null,
    paid_at: 1752836016,
    voided_at: null,
  },
  subtotal: 0,
  subtotal_excluding_tax: 0,
  test_clock: null,
  total: 0,
  total_discount_amounts: [],
  total_excluding_tax: 0,
  total_pretax_credit_amounts: [],
  total_taxes: [],
  webhooks_delivered_at: null,
};

const deletingSubscription = {
  id: "sub_1RgAlNLAxh7V2BxL0HJi8iCh",
  object: "subscription",
  application: null,
  application_fee_percent: null,
  automatic_tax: { disabled_reason: null, enabled: false, liability: null },
  billing_cycle_anchor: 1752006404,
  billing_cycle_anchor_config: null,
  billing_mode: { type: "classic" },
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: 1753096891,
  cancellation_details: {
    comment: null,
    feedback: null,
    reason: "cancellation_requested",
  },
  collection_method: "charge_automatically",
  created: 1751401604,
  currency: "gbp",
  customer: "cus_SbNW2tqZBzSL46",
  days_until_due: null,
  default_payment_method: "pm_1RgAlLLAxh7V2BxLRIHLClFo",
  default_source: null,
  default_tax_rates: [],
  description: null,
  discounts: [],
  ended_at: 1753096891,
  invoice_settings: { account_tax_ids: null, issuer: { type: "self" } },
  items: {
    object: "list",
    data: [[Object]],
    has_more: false,
    total_count: 1,
    url: "/v1/subscription_items?subscription=sub_1RgAlNLAxh7V2BxL0HJi8iCh",
  },
  latest_invoice: "in_1Rii72LAxh7V2BxLCQZ5mdoP",
  livemode: false,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: {
      acss_debit: null,
      bancontact: null,
      card: [Object],
      customer_balance: null,
      konbini: null,
      sepa_debit: null,
      us_bank_account: null,
    },
    payment_method_types: null,
    save_default_payment_method: "off",
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    id: "price_1RfmqFLAxh7V2BxLt2hMnLTc",
    object: "plan",
    active: true,
    amount: 1299,
    amount_decimal: "1299",
    billing_scheme: "per_unit",
    created: 1751309651,
    currency: "gbp",
    interval: "month",
    interval_count: 1,
    livemode: false,
    metadata: {},
    meter: null,
    nickname: null,
    product: "prod_Sayn8WtloqIH6C",
    tiers_mode: null,
    transform_usage: null,
    trial_period_days: null,
    usage_type: "licensed",
  },
  quantity: 1,
  schedule: null,
  start_date: 1751401604,
  status: "canceled",
  test_clock: null,
  transfer_data: null,
  trial_end: 1752006404,
  trial_settings: {
    end_behavior: { missing_payment_method: "create_invoice" },
  },
  trial_start: 1751401604,
};

const createCustomer = {
  id: "cus_SilDtHpr8Bapub",
  object: "customer",
  address: null,
  balance: 0,
  created: 1753104202,
  currency: null,
  default_source: null,
  delinquent: false,
  description: "test customer 1",
  discount: null,
  email: "pokax27563@dosonex.com",
  invoice_prefix: "7RLKZ8TO",
  invoice_settings: {
    custom_fields: null,
    default_payment_method: null,
    footer: null,
    rendering_options: null,
  },
  livemode: false,
  metadata: {},
  name: "Pokax Dosonex",
  phone: null,
  preferred_locales: [],
  shipping: null,
  tax_exempt: "none",
  test_clock: null,
};

const createSubSession = {
  id: "in_1RpsmvLAxh7V2BxL7qTi6ukV",
  object: "invoice",
  account_country: "GB",
  account_name: "Virstaf LTD",
  account_tax_ids: null,
  amount_due: 1299,
  amount_overpaid: 0,
  amount_paid: 1299,
  amount_remaining: 0,
  amount_shipping: 0,
  application: null,
  attempt_count: 0,
  attempted: true,
  auto_advance: false,
  automatic_tax: {
    disabled_reason: null,
    enabled: false,
    liability: null,
    provider: null,
    status: null,
  },
  automatically_finalizes_at: null,
  billing_reason: "subscription_create",
  collection_method: "charge_automatically",
  created: 1753715789,
  currency: "gbp",
  custom_fields: null,
  customer: "cus_SlPTJ9c40jXRpr",
  customer_address: null,
  customer_email: "jivoj62790@7tul.com",
  customer_name: null,
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: "none",
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discounts: [],
  due_date: null,
  effective_at: 1753715789,
  ending_balance: 0,
  footer: null,
  from_invoice: null,
  hosted_invoice_url:
    "https://invoice.stripe.com/i/acct_1L35V5LAxh7V2BxL/test_YWNjdF8xTDM1VjVMQXhoN1YyQnhMLF9TbFBjYUY5U1lOQWNHVWVXMnpPbVBzbGM4TFF5UVNvLDE0NDI1NjU5Mg0200hDI5yPew?s=ap",
  invoice_pdf:
    "https://pay.stripe.com/invoice/acct_1L35V5LAxh7V2BxL/test_YWNjdF8xTDM1VjVMQXhoN1YyQnhMLF9TbFBjYUY5U1lOQWNHVWVXMnpPbVBzbGM4TFF5UVNvLDE0NDI1NjU5Mg0200hDI5yPew/pdf?s=ap",
  issuer: { type: "self" },
  last_finalization_error: null,
  latest_revision: null,
  lines: {
    object: "list",
    data: [[Object]],
    has_more: false,
    total_count: 1,
    url: "/v1/invoices/in_1RpsmvLAxh7V2BxL7qTi6ukV/lines",
  },
  livemode: false,
  metadata: {},
  next_payment_attempt: null,
  number: "1AF11EFE-0074",
  on_behalf_of: null,
  parent: {
    quote_details: null,
    subscription_details: {
      metadata: [Object],
      subscription: "sub_1RpsmxLAxh7V2BxLa6wTwuuJ",
    },
    type: "subscription_details",
  },
  payment_settings: {
    default_mandate: null,
    payment_method_options: {
      acss_debit: null,
      bancontact: null,
      card: [Object],
      customer_balance: null,
      konbini: null,
      sepa_debit: null,
      us_bank_account: null,
    },
    payment_method_types: null,
  },
  period_end: 1753715789,
  period_start: 1753715789,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  receipt_number: null,
  rendering: null,
  shipping_cost: null,
  shipping_details: null,
  starting_balance: 0,
  statement_descriptor: null,
  status: "paid",
  status_transitions: {
    finalized_at: 1753715789,
    marked_uncollectible_at: null,
    paid_at: 1753715790,
    voided_at: null,
  },
  subtotal: 1299,
  subtotal_excluding_tax: 1299,
  test_clock: null,
  total: 1299,
  total_discount_amounts: [],
  total_excluding_tax: 1299,
  total_pretax_credit_amounts: [],
  total_taxes: [],
  webhooks_delivered_at: null,
};

// Creating subscription action with session: {
//   id: 'sub_1RpsmxLAxh7V2BxLa6wTwuuJ',
//   object: 'subscription',
//   application: null,
//   application_fee_percent: null,
//   automatic_tax: { disabled_reason: null, enabled: false, liability: null },
//   billing_cycle_anchor: 1753715789,
//   billing_cycle_anchor_config: null,
//   billing_mode: { type: 'classic' },
//   billing_thresholds: null,
//   cancel_at: null,
//   cancel_at_period_end: false,
//   canceled_at: null,
//   cancellation_details: { comment: null, feedback: null, reason: null },
//   collection_method: 'charge_automatically',
//   created: 1753715789,
//   currency: 'gbp',
//   customer: 'cus_SlPTJ9c40jXRpr',
//   days_until_due: null,
//   default_payment_method: 'pm_1RpsmuLAxh7V2BxLy7PcWUeU',
//   default_source: null,
//   default_tax_rates: [],
//   description: null,
//   discounts: [],
//   ended_at: null,
//   invoice_settings: { account_tax_ids: null, issuer: { type: 'self' } },
//   items: {
//     object: 'list',
//     data: [ [Object] ],
//     has_more: false,
//     total_count: 1,
//     url: '/v1/subscription_items?subscription=sub_1RpsmxLAxh7V2BxLa6wTwuuJ'
//   },
//   latest_invoice: 'in_1RpsmvLAxh7V2BxL7qTi6ukV',
//   livemode: false,
//   metadata: { userId: '7ceb81f3-6e41-485e-b995-966685a17605' },
//   next_pending_invoice_item_invoice: null,
//   on_behalf_of: null,
//   pause_collection: null,
//   payment_settings: {
//     payment_method_options: {
//       acss_debit: null,
//       bancontact: null,
//       card: [Object],
//       customer_balance: null,
//       konbini: null,
//       sepa_debit: null,
//       us_bank_account: null
//     },
//     payment_method_types: null,
//     save_default_payment_method: 'off'
//   },
//   pending_invoice_item_interval: null,
//   pending_setup_intent: null,
//   pending_update: null,
//   plan: {
//     id: 'price_1RfmqFLAxh7V2BxLt2hMnLTc',
//     object: 'plan',
//     active: true,
//     amount: 1299,
//     amount_decimal: '1299',
//     billing_scheme: 'per_unit',
//     created: 1751309651,
//     currency: 'gbp',
//     interval: 'month',
//     interval_count: 1,
//     livemode: false,
//     metadata: {},
//     meter: null,
//     nickname: null,
//     product: 'prod_Sayn8WtloqIH6C',
//     tiers_mode: null,
//     transform_usage: null,
//     trial_period_days: null,
//     usage_type: 'licensed'
//   },
//   quantity: 1,
//   schedule: null,
//   start_date: 1753715789,
//   status: 'active',
//   test_clock: null,
//   transfer_data: null,
//   trial_end: null,
//   trial_settings: { end_behavior: { missing_payment_method: 'create_invoice' } },
//   trial_start: null
// }

const dbError = {
  code: "23514",
  details:
    "Failing row contains (7ceb81f3-6e41-485e-b995-966685a17605, jivoj62790@7tul.com, jivoj_tul, null, Jivoj Tul, null, null, 2025-07-28 14:37:58.451878+00, V758264, null, jivoj62790@7tul.com, USER, null, t, 2025-08-28 15:16:29, cus_SlPTJ9c40jXRpr, active, null, null, paid_plan, sub_1RpsmxLAxh7V2BxLa6wTwuuJ).",
  hint: null,
  message:
    'new row for relation "profiles" violates check constraint "profiles_subscription_plan_check"',
};
