-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  page_path text NOT NULL,
  page_id text,
  note_content text,
  admin_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_notes_pkey PRIMARY KEY (id),
  CONSTRAINT admin_notes_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES auth.users(id)
);
CREATE TABLE public.blog_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blog_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  excerpt text,
  content text NOT NULL,
  featured_image text,
  category_id uuid,
  author_id uuid,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text])),
  published_at timestamp with time zone,
  reading_time integer,
  views integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id),
  CONSTRAINT blog_posts_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.blog_categories(id),
  CONSTRAINT blog_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id)
);
CREATE TABLE public.contact-form (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  fullname text NOT NULL DEFAULT ''::text,
  email text NOT NULL,
  message text NOT NULL,
  CONSTRAINT contact-form_pkey PRIMARY KEY (id)
);
CREATE TABLE public.deals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  partner_id uuid,
  title text NOT NULL,
  description text NOT NULL,
  discount_percentage integer,
  discount_amount numeric,
  start_date date NOT NULL,
  end_date date NOT NULL,
  promo_code text,
  terms_conditions text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status text,
  image_url text,
  package_type text,
  duration_nights integer DEFAULT 4,
  includes_flight boolean DEFAULT true,
  original_price numeric,
  location text,
  is_featured boolean DEFAULT false,
  includes_hotel boolean,
  includes_transfer boolean,
  location_prices jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT deals_pkey PRIMARY KEY (id),
  CONSTRAINT deals_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.partners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['hotel'::text, 'resort'::text, 'lounge'::text, 'airline'::text])),
  location text NOT NULL,
  description text,
  amenities ARRAY,
  images ARRAY,
  contact_email text,
  website_url text,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text UNIQUE,
  username text UNIQUE,
  phone text UNIQUE,
  full_name text,
  avatar_url text,
  bio text,
  updated_at timestamp with time zone DEFAULT now(),
  customer_id text NOT NULL UNIQUE,
  website text,
  public_email text,
  role text NOT NULL,
  country text,
  is_subscribed boolean DEFAULT false,
  subscription_end timestamp without time zone,
  stripe_customer_id text,
  subscription_status text DEFAULT 'inactive'::text,
  trial_ends_at timestamp with time zone,
  trial_start timestamp with time zone,
  subscription_plan text DEFAULT 'inactive'::text CHECK (subscription_plan = ANY (ARRAY['inactive'::text, 'trial'::text, 'silver'::text, 'gold'::text, 'platinum'::text])),
  subscription_plan_id text,
  home_country text,
  preferred_destinations ARRAY,
  travel_frequency text,
  onboarding_completed boolean DEFAULT false,
  membership_tier text DEFAULT 'Gold'::text,
  date_of_birth date,
  address_line1 text,
  address_line2 text,
  city text,
  postal_code text,
  billing_country text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.quote_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  reservation_id uuid NOT NULL,
  reservation_type text NOT NULL CHECK (reservation_type = ANY (ARRAY['flight'::text, 'hotel'::text, 'transfer'::text])),
  category text NOT NULL,
  description text NOT NULL,
  supplier text,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  quantity integer DEFAULT 1 CHECK (quantity > 0),
  subtotal numeric DEFAULT (price * (quantity)::numeric),
  is_selected boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_items_pkey PRIMARY KEY (id),
  CONSTRAINT quote_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT quote_items_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservations(id)
);
CREATE TABLE public.quote_revisions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  version integer NOT NULL CHECK (version > 0),
  changes_summary text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_revisions_pkey PRIMARY KEY (id),
  CONSTRAINT quote_revisions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT quote_revisions_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trip_id uuid,
  quote_number text NOT NULL UNIQUE,
  version integer DEFAULT 1,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'accepted'::text, 'rejected'::text, 'revised'::text, 'expired'::text])),
  admin_notes text,
  client_notes text,
  total_amount numeric,
  valid_until date,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  rejection_reason text,
  rejection_note text,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT quotes_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT quotes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.reservations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid,
  user_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['flight'::text, 'hotel'::text, 'transfer'::text])),
  details jsonb NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in review'::text, 'confirmed'::text, 'active'::text, 'completed'::text, 'expired'::text, 'cancelled'::text, 'rejected'::text, 'quote_sent'::text, 'payment_pending'::text, 'processing'::text])),
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  special_request text,
  ref_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
  quote_id uuid,
  CONSTRAINT reservations_pkey PRIMARY KEY (id),
  CONSTRAINT reservations_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT reservations_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT reservations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.subscriptions (
  id text NOT NULL,
  user_id uuid NOT NULL UNIQUE,
  user_email text NOT NULL,
  plan text NOT NULL UNIQUE,
  status text NOT NULL,
  current_period_start timestamp with time zone NOT NULL,
  current_period_end timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  description text,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.trips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  destination character varying NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  budget numeric,
  adults integer DEFAULT 1,
  children integer DEFAULT 0,
  status character varying DEFAULT 'planning'::character varying CHECK (status::text = ANY (ARRAY['planning'::character varying::text, 'booked'::character varying::text, 'in_progress'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text])),
  is_public boolean DEFAULT false,
  cover_image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  location character varying,
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);